x-common-service: &common-service
    image: "endy_soft/gz"
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - .env

services:
  db_migrations:
    <<: *common-service

    command: ["python3", "manage.py", "migrate", "--noinput"]
    depends_on:
      postgres:
        condition: service_healthy
  init:
    <<: *common-service
    command: ["/bin/sh", "-c", "/usr/src/scripts/init.sh"]
    depends_on:
      db_migrations:
        condition: service_completed_successfully
  app:
    <<: *common-service
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - ${EXPOSED_HTTP_PORT}:8000
    depends_on:
      postgres:
        condition: service_healthy
      init:
        condition: service_completed_successfully
    restart: on-failure

  postgres:
    image: postgres:15

    ports:
      - ${EXPOSED_POSTGRES_PORT}:${DB_PORT}
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    command: -p ${DB_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -p ${DB_PORT}" ]
      interval: 1s
      start_period: 5s
